jobs:
  - script: >
      job("terraform-job") {
         description()
         keepDependencies(false)
         disabled(false)
         concurrentBuild(false)
         wrappers {
            terraformBuildWrapper {
               variables("") 
               terraformInstallation("terraform")
               doGetUpdate(true)
               doNotApply(false)
               doDestroy(false)
               config {
                  value("inline")
                  inlineConfig("")
                  fileConfig("")
               }
            }
         }
      }
  - script: >
      multibranchPipelineJob('django-cms') {
         branchSources {
            git {
               credentialsId('github-key')
               remote('git@github.com:tuxtek/django-cms.git')
            }
         }
         orphanedItemStrategy {
            discardOldItems {
               numToKeep(20)
            }
         }
      }
